CREATE TABLE PORTOWN.SPEC_TAX (
    SPEC_ID        INTEGER PRIMARY KEY,
    SPEC_DS        VARCHAR(255),
    TAXONOMY_ID    INTEGER,
    TAXONOMY       VARCHAR(50)
);

CREATE OR REPLACE VIEW PORTOWN.V_SPEC_TAX AS
SELECT SPEC_ID, SPEC_DS, TAXONOMY_ID, TAXONOMY
FROM PORTOWN.SPEC_TAX;