version: 1
disable_existing_loggers: False

formatters:
  text:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

  json:
    class: logging.Formatter
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: ${LOG_CONSOLE_FORMAT:-text}
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: ${LOG_FILE_FORMAT:-json}
    filename: logs/aton-mock-data.log
    maxBytes: 5000000
    backupCount: 3

loggers:
  urllib3:
    level: WARNING
    handlers: []
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]